### ISSUE TITLE
Make author name look clickable

### ISSUE THREAD

**Issue by damithc** [se-edu/RepoSense#29]
![image](https://user-images.githubusercontent.com/1673303/37821306-339c8556-2ebe-11e8-8a5a-887c35508b1a.png)

The current version doesn't look clickable. i.e., mouse icon doesn't change when hovering over.

Also, we can add a small icon to the end of the name to give a target for the user to click.

> 124. CS2103JAN2018-W10-B4/main/NG JU...N WEI ▶️

**Comment by harryggg** [comment]
fixed
