### ISSUE TITLE
File name with spaces

### ISSUE THREAD

**Issue by harryggg** [se-edu/RepoSense#52]
CommandRunner has trouble processing file name with spaces. Need to add escape character. Note: Windows and UNIX have different escape characters.

**Comment by damithc** [comment]
The usual solution used by other CLI programs is to require double quotes around any parameter that has spaces inside it.

**Comment by harryggg** [comment]
Ya I am wrapping all file names with quotes. Thx for the suggestion!

**Comment by harryggg** [comment]
fixed
