### ISSUE TITLE
No contributors in the dashboard

### ISSUE THREAD

**Issue by damithc** [se-edu/RepoSense#55]
This config file produces an empty dashboard. Not sure what I'm doing wrong. I'm using the latest version of reposense.

(rename file to .csv)

[se-edu.txt](https://github.com/se-edu/RepoSense/files/1934348/se-edu.txt)

**Comment by harryggg** [comment]
I think you put their Email instead of Git ID... it should be Zhiyuan-Amos instead

**Comment by damithc** [comment]
`Zhiyuan-Amos` is his GitHub username. How to find the Git ID?

**Comment by harryggg** [comment]
"Zhi Yuan Yong" is his alias, Zhiyuan-Amos is his Git ID.

**Comment by harryggg** [comment]
<img width="1262" alt="screen shot 2018-04-21 at 7 28 13 pm" src="https://user-images.githubusercontent.com/1697432/39083648-3aedd1aa-459a-11e8-8e70-3c42868d8dfb.png">

**Comment by harryggg** [comment]
[se-edu.txt](https://github.com/se-edu/RepoSense/files/1934434/se-edu.txt)
If there are more alias ,just link them semicolon.

**Comment by damithc** [comment]
It's working. Thanks.
