### ISSUE TITLE
LoC without Ramps

### ISSUE THREAD

**Issue by damithc** [se-edu/RepoSense#61]
For this dev, there are no ramps, but there is some code. Is this possible? No collate tags used.
![image](https://user-images.githubusercontent.com/1673303/39421494-e28feaf8-4c9b-11e8-9dd2-615da5d4fc2e.png)

config:
[cs3282.txt](https://github.com/se-edu/RepoSense/files/1960077/cs3282.txt)

**Comment by harryggg** [comment]
She uses two local author name Joanne Ong Cui Fang and Joanne Ong. That's why no ramp chart is showing, and the code panel only shows part of her contribution. If we use both email and user id as identifier as suggested in #41 , we can spend less time figuring out this kind of isssue(hopefully).

**Comment by damithc** [comment]
So the ramp chart and code panel are based on two different sets of data?  I thought if we miss some commits due to the use of different aliases, both ramp chart and the code panel should miss that code consistently.

**Comment by damithc** [comment]
Or is this due to squashing? i.e., The squashed commit contains code under multiple aliases but the commit is tied to only one alias? That way, no commits are identified for the known alias but some code is identified by git blame for the same alias.

**Comment by harryggg** [comment]
Yes... Ramp chart is based on Git Log, and code panel is based on Git blame... I think it is  the only way to do it, if we use git blame to produce ramp chart, it will take half a day to analyze one repo.

**Comment by damithc** [comment]
Got it.
